spring:
database:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/postgres
  username: alexandr
  password: krylov

liquibase:
  change-log: classpath:db/changelog/changelog-master.xml
  enabled: true
